ckptint: 10
dataset: irregular_varicoef_diff_conv_eqn_4nn_42_100sample
device: cuda:1
epochnum: 2000
eval_batch_size: 32
expdir: ''
extconf: ''
graph: 4nn
hidden_dim: 64
invsig_delay_start: 0
invsig_ss_itern: 1000
layer_num: 3
lr: 0.002
mode: train
model: LinearRegOp_Standard
noaa_given_input_features: ''
noaa_target_features: TEMP
optim: Adam
pde_mode: diff
pde_params_out_dim: null
reinit_optimizer: 'False'
resroot: ../artifacts/iclrexps
return_features: 'False'
sample_scheduler: inverse_sigmoid
seed: 42
skip_first_frames_num: 5
specify_ckpt: ''
testint: 100
train_batch_size: 32
use_dist: 'False'
validint: 1
