ckptint: 10
dataset: sst-daily_4nn_42_250sample
device: cuda:1
epochnum: 2000
eval_batch_size: 4
expdir: ''
extconf: ''
graph: de
hidden_dim: 64
invsig_delay_start: 0
invsig_ss_itern: 1000
layer_num: 3
lr: 0.001
mode: train
model: GraphPDE_GN_RGN_16_notshared
noaa_given_input_features: ''
noaa_target_features: TEMP
node_meta_suffix: ''
optim: Adam
pde_mode: diff
pde_params_out_dim: null
reinit_optimizer: 'False'
resroot: ../artifacts/iclrexps
return_features: 'False'
sample_scheduler: inverse_sigmoid
seed: 42
skip_first_frames_num: 5
specify_ckpt: ''
testint: 100
train_batch_size: 4
use_dist: 'False'
validint: 1
