ckptint: 10
dataset: noaa_ec_states_test_2_withloc
device: cuda:0
epochnum: 2000
eval_batch_size: 16
expdir: ''
extconf: ''
graph: 4nn
hidden_dim: 64
invsig_ss_itern: 1000
layer_num: 3
lr: 0.001
mode: train
model: SingleMLP
noaa_given_input_features: ''
noaa_target_features: TEMP
optim: Adam
pde_mode: diff
pde_params_out_dim: null
reinit_optimizer: 'False'
resroot: ../artifacts/iclrexps
return_features: 'False'
sample_scheduler: inverse_sigmoid
seed: 43
skip_first_frames_num: 12
specify_ckpt: ''
testint: 100
train_batch_size: 16
use_dist: 'False'
validint: 1
